version: '2.1'

services:

  retail-rabbitmq:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Queue
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 10s
      retries: 5



  retail-frontend:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Frontend
    ports:
      - '5000:80'



  retail-catalog:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Catalog
    ports:
      - '5001:80'
    depends_on:
      retail-catalog-database:
        condition: service_healthy
    links:
      - retail-catalog-database

  retail-catalog-database:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=retail
      - POSTGRES_DB=catalog
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  retail-catalog-frontend:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Catalog.Frontend
    ports:
      - '6001:80'



  retail-sales:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Sales
    ports:
      - '5002:80'
    depends_on:
      retail-rabbitmq:
        condition: service_healthy
    links: 
        - retail-rabbitmq
    stdin_open: true
    tty: true

  retail-sales-microfrontend:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Sales.Microfrontend
    ports:
      - '6002:80'



  retail-billing:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Billing
    depends_on:
      retail-rabbitmq:
        condition: service_healthy
    links: 
        - retail-rabbitmq
    stdin_open: true
    tty: true



  retail-shipping:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Shipping
    depends_on:
      retail-rabbitmq:
        condition: service_healthy
    links: 
        - retail-rabbitmq
    stdin_open: true
    tty: true



  retail-recommendations:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Recommendations
    depends_on:
      retail-rabbitmq:
        condition: service_healthy
    links: 
        - retail-rabbitmq
        - retail-recommendations-database
    stdin_open: true
    tty: true

  retail-recommendations-database:
    build:
      dockerfile: Dockerfile
      context: ./Retail.Recommendations.Database
    ports:
      - 7474:7474
      - 7687:7687
    environment: 
      - NEO4J_AUTH=none
